[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "riscv64gc-unknown-none-elf -machine virt -cpu rv64 -bios none -nographic -serial mon:stdio --no-reboot -m 128M -kernel "

rustflags = [
    "-C",
    "link-arg=-Tkernel.ld",
    "-C",
    "link-arg=-Map=target/kernel.map",
    "-C",
    "link-arg=--verbose",
]
[env]
RUSTC_LOG = "rustc_codegen_ssa::back::link=info"
