[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -bios none -nographic -serial mon:stdio --no-reboot -m 128M -kernel "
rustflags = [
    "--cfg",
    "feature=\"board_qemu_virt\"",
    "-C",
    "link-arg=-Tkernel.ld",
    "-C",
    "link-arg=-Map=target/kernel.map",
    # uncomment this to get verbose output to debug linking phase
    # "-C",
    # "link-arg=--verbose",
]

[env]
# RUSTC_LOG = "rustc_codegen_ssa::back::link=info"
